name: CLRT Build/Release

on:
  push:
    # takes muliple branch names
    branches: 
      - main
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].*' # 2021.01.x
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]' # 2021.01.01
  pull_request:
    branches:
      - main
 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'YYYY.MINOR.MICRO'
env:
  REPO_URL: ${{ github.repository }}
    
jobs:
  build:
    # to test a feature, change the repo name to your github id
    if: github.repository_owner == 'tl-its-umich-edu'
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code 
        uses: actions/checkout@v4
    
      - name: Extract branch or PR number
        id: extract_branch_or_pr
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BRANCH_OR_PR=pr-${{ github.event.number }}" >> $GITHUB_ENV
          else
            echo "BRANCH_OR_PR=$(basename ${{ github.ref }})" >> $GITHUB_ENV
          fi
      
      - name: build Docker image
        run: |
          docker build . --tag ghcr.io/${{ env.REPO_URL }}:${BRANCH_OR_PR}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ env.REPO_URL }}:${BRANCH_OR_PR}    
      

